# Generated by Django 5.2.4 on 2025-07-31 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, verbose_name='номер аудитории')),
                ('lectures', models.BooleanField(blank=True, verbose_name='Можно ли проводить лекции')),
                ('studies', models.BooleanField(blank=True, verbose_name='Можно ли проводить семинары')),
                ('praktical_work', models.BooleanField(blank=True, verbose_name='Можно ли проводить лабораторные работы')),
                ('available_on_monday', models.BooleanField(blank=True, verbose_name='доступна в пн')),
                ('available_on_tuesday', models.BooleanField(blank=True, verbose_name='доступна в вт')),
                ('available_on_wednesday', models.BooleanField(blank=True, verbose_name='доступна в ср')),
                ('available_on_thursday', models.BooleanField(blank=True, verbose_name='доступна в чт')),
                ('available_on_friday', models.BooleanField(blank=True, verbose_name='доступна в пт')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название предмета')),
                ('lectures', models.SmallIntegerField(blank=True, verbose_name='Кол-во лекций в неделю')),
                ('studies', models.SmallIntegerField(blank=True, verbose_name='Кол-во семинаров в неделю')),
                ('praktical_work', models.SmallIntegerField(blank=True, verbose_name='Кол-во лабораторных работ в неделю')),
                ('hardness', models.SmallIntegerField(blank=True, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя учителя')),
                ('lectures', models.BooleanField(blank=True, verbose_name='Может ли проводить лекции')),
                ('studies', models.BooleanField(blank=True, verbose_name='Может ли проводить семинары')),
                ('praktical_work', models.BooleanField(blank=True, verbose_name='Может ли проводить лабораторные работы')),
                ('available_on_monday', models.BooleanField(blank=True, verbose_name='доступен в пн')),
                ('available_on_tuesday', models.BooleanField(blank=True, verbose_name='доступен в вт')),
                ('available_on_wednesday', models.BooleanField(blank=True, verbose_name='доступен в ср')),
                ('available_on_thursday', models.BooleanField(blank=True, verbose_name='доступен в чт')),
                ('available_on_friday', models.BooleanField(blank=True, verbose_name='доступен в пт')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TimeTable_App.Subjects', verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['id'],
            },
        ),
    ]
