# Generated by Django 5.2.4 on 2025-07-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название предмета'),
        ),
    ]
