# Generated by Django 5.2.4 on 2025-07-31 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_App', '0002_alter_subjects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeTable_App.subjects', verbose_name='Название предмета'),
        ),
    ]
