# Generated by Django 5.2.4 on 2025-08-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_App', '0003_alter_teachers_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TimeTable_App.subjects', verbose_name='Название предмета'),
        ),
    ]
