# Generated by Django 5.2.4 on 2025-08-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_App', '0004_alter_subjects_title_alter_teachers_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='subject',
        ),
    ]
