# Generated by Django 5.2.4 on 2025-08-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_App', '0005_remove_teachers_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TimeTable_App.subjects', verbose_name='Название предмета'),
        ),
    ]
